# -- modalities related
modalities:
 - caption
 - image
 - text

# -- languages related
languages:
 - english
 - spanish

# -- model architecture related
model: pink_baseline
model_conf:
  input_dim: 768
  latent_dim: 256
  n_head: 8
  num_encoder_layers: 6
  dim_feedforward: 2048
  modality_masking_prob: 0.0


# -- training settings related
training_settings:
  optimizer: 'adamw'
  scheduler: 'onecycle'
  anneal_strategy: 'linear'
  loss_criterion: 'cross_entropy'
  epochs: 20
  batch_size: 16
  learning_rate: 0.002
  num_workers: 8

# -- implementation related
num_classes: 2
class_name:
 - misoginy
 - no-misoginy

device: 'cuda'
