# -- modalities related
modalities:
 - clip_caption
 - clip_image
 - clip_text

# -- languages related
languages:
 - en
 - es

# -- model architecture related
model: pink_mlp
model_conf:
  input_dim: 512
  latent_dim: 256
  mlp_dim: 1024
  modality_masking_prob: 0.0

# -- training settings related
training_settings:
  optimizer: 'adamw'
  scheduler: 'onecycle'
  anneal_strategy: 'linear'
  loss_criterion: 'cross_entropy'
  epochs: 20
  batch_size: 8
  learning_rate: 0.0005
  num_workers: 6

# -- task related
num_classes: 7
class_names:
 - 0.0
 - 0.1666
 - 0.3333
 - 0.5
 - 0.6666
 - 0.8333
 - 1.0
task: 'soft_label_task4'
device: 'cuda'
