# -- modalities related
modalities:
 - clip_caption
 - clip_image
 - clip_text
 - bert_caption
 - bert_text

# -- languages related
languages:
 - en
 - es

# -- model architecture related
model: pink_mlp
model_conf:
  latent_dim: 256
  mlp_dim: 1024
  dropout: 0.1
  use_modality_emb: true
  use_language_emb: true
  modality_masking_prob: 0.0

# -- training settings related
training_settings:
  optimizer: 'adamw'
  scheduler: 'onecycle'
  anneal_strategy: 'linear'
  loss_criterion: 'cross_entropy'
  epochs: 20
  batch_size: 8
  learning_rate: 0.0005
  num_workers: 6

# -- task related
num_classes: 2
class_names:
 - sexism
 - no-sexism
task: 'soft_label_task4'
device: 'cuda'
